Fix documentation in Presto flows
s1mbi0se/presto pull request #59
Opened 2020-10-28 00:10 UTC by anthonylouisbsb

# Pull Request Merge Checklist
           
Task backlog identifier related to this PR: ---

---

## As a DEVELOPER, I confirm that this PR **doesn't contain**:
- [x] Code lines with syntax errors
- [x] Methods and variables names that aren't clear or doesn't mean anything
- [x] Code that is out of the standard (Example: **PEP-8** for Python code)
- [x] Files with **imports** errors or without any utility
- [x] **TODOs** left behind
- [x] Tests that are being skipped
- [x] Methods placed on incorrect files or folders (Example: methods that are local, but should be placed on /utils)
- [x] Functions, methods or API responses that are publicly returning sensitive information

## As a DEVELOPER, I confirm that I:
- [x] Followed the Simbiose's standard for branch and commit naming
- [x] Concluded the task and achieved the goals according to the task planning I defined before starting to code
- [x] Added all necessary database changes to the [SQL Migrations](https://github.com/s1mbi0se/sql-migrations)
- [x] Created tests for every new flow and method on this Pull Request
- [x] Added the necessary DEBUG logs
- [x] Checked my code using the Simbiose's Corner Cases Guide
- [x] Merged the **develop** branch to this PR/branch before sending the PR for review
- [x] Solved all possible merge conflicts before sending the PR for review
- [x] Corrected all the problems and code smells identified by the quality tools
- [x] Manually executed the necessary tests locally to make sure my changes didn't break anything
- [x] All unitary and integration tests ran by the CI system are passing
- [x] Check the performance of my changes or additions and they didn't make the system slower (I profiled the code)
- [x] Updated the necessary documentation (Example: OpenAPI, Docstrings, Metadata Database Modeling)
- [x] Made the self-review of the code before sending the PR for review
- [x] Sent this PR for a peer-review
- [x] Made all the corrections appointed during the peer-review
- [x] Confirmed that this PR merge will not cause other systems or dependencies to stop working (Example: ShannonDB Python Client and ShannonDB)
- [x] Checked all GitHub Actions related to this PR that can block my merge

---  

## As the TEAM MANAGER, I confirm that I:
- [ ] Checked that the code was developed following the best practices for the language, with the best possible readability and using the less possible quantity of code lines and complexity. 
- [ ] Checked if the Pull Request and commit messages follow the Simbiose’s defined standard 
- [ ] Checked if there is no possible merge conflicts before reviewing the PR
- [ ] Checked if the purpose of the task was reached with this PR
- [ ] Checked that the code was developed following the best practices for the language, with the best possible readability and using the less possible quantity of code lines and complexity. 
- [ ] Checked if all related PRs were created when other components were affected by this task (e.g. database changes on [SQL Migrations](https://github.com/s1mbi0se/sql-migrations))
- [ ] Checked that were created unit, integration and chaos tests for every new flow and method on this Pull Request
- [ ] Checked that no sensible information (e.g. users security data, internal security data, etc) was exposed by this PR
- [ ] Checked that code coverage for this PR is higher than 80%.
- [ ] Checked that there are no problems and code smells identified by the quality and security tools
- [ ] Checked that all files were created on the proper folders according to the Simbiose’s defined standard
- [ ] Checked that all classes, methods and variables on this PR follow the Simbiose’s pattern for this programming language
- [ ] Checked that all unitary and integration tests ran by the CI system are passing
- [ ] Checked that there are no performance issues created by these changes or additions
- [ ] Checked that all documentation is up to date according to this change (Example: OpenAPI, Docstrings, Metadata Database Modeling)
- [ ] Checked that this PR merge will not cause other systems or dependencies to stop working (Example: ShannonDB Python Client and ShannonDB)
- [ ] Checked all GitHub Actions related to this PR that can block the merge

---  

## As the QUALITY RESPONSIBLE, I confirm that I:
- [ ] Checked if the Pull Request and commit messages follow the Simbiose’s defined standard 
- [ ] Checked if there is no possible merge conflicts before reviewing the PR
- [ ] Checked that were created unit, integration and chaos tests for every new flow and method on this Pull Request
- [ ] Checked that no sensible information (e.g. users security data, internal security data, etc) was exposed by this PR
- [ ] Checked that code coverage for this PR is higher than 80%.
- [ ] Checked that there are no problems and code smells identified by the quality and security tools
- [ ] Checked that all files were created on the proper folders according to the Simbiose’s defined standard
- [ ] Checked that all classes, methods and variables on this PR follow the Simbiose’s code standard for this programming language
- [ ] Checked that all unitary and integration tests ran by the CI system are passing
- [ ] Checked that there are no performance issues created by these changes or additions
- [ ] Checked that all documentation is up to date according to this change (Example: OpenAPI, Docstrings, Metadata Database Modeling)
- [ ] Checked that this PR merge will not cause other systems or dependencies to stop working (Example: ShannonDB Python Client and ShannonDB)
- [ ] Checked all GitHub Actions related to this PR that can block the merge

## Important links:
1. [Simbiose Quality Guidelines](https://github.com/s1mbi0se/company/wiki/Quality-Topics#table-of-contents)
2. [Metadata Database Modeling](https://docs.google.com/spreadsheets/d/1Y8_k5xV86kTjgfjbi-PGsJcubUKhWlT2x8ecpnMlyR0/edit?usp=sharing)
3. [Simbiose's Corner Cases Guide](https://www.simbioseventures.com/documentos-e-guias/procedimentos-e-checklists/corner-cases-guide)

2020-10-28 14:14 UTC, joaopedro-simbiose requested changes

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/sql/planner/PartitioningScheme.java
> +     * Gets the type that the partition is represented.
```suggestion
     * Gets the type that the partition is representing.
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/sql/planner/PartitioningScheme.java
> +     * @return the type that the partition is represented
```suggestion
     * @return the type that the partition is representing
```
```suggestion
     * @return the type that the partition is represented
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/sql/planner/OrderingScheme.java
> +     * Gets the all ORDER BY clauses.
```suggestion
     * Gets all the defined ORDER BY clauses.
```
Where are these clauses defined?

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/server/protocol/Query.java
> +     * Wait for results of te query processing.
```suggestion
     * Waits for results of the query processing.
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/server/protocol/Query.java
> +     * @param wait the maximum time to wait query response
```suggestion
     * @param wait the maximum time to wait for query response
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/server/protocol/Query.java
> +     * @return the result of query processing
```suggestion
     * @return the result of the query processing
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/server/protocol/ExecutingStatementResource.java
> +     * Gets the results for a executing query.
```suggestion
     * Gets the results for an executing query.
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/server/protocol/ExecutingStatementResource.java
> +     * @param maxWait the maximum time to wait query response
```suggestion
     * @param maxWait the maximum time to wait for query response
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/server/protocol/ExecutingStatementResource.java
> +     * @param maxWait the maximum time to wait query response
```suggestion
     * @param maxWait the maximum time to wait for query response
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/server/TaskResource.java
> +    /**
No summary?

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/server/TaskResource.java
> +     * @param waitTime the max time to wait query to be processed
```suggestion
     * @param waitTime the max time to wait for the query to be processed
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/metadata/HandleResolver.java
> +         * Gets the class used to tell the partition scheme of the query execution.
```suggestion
         * Gets the class used to inform the partition scheme about the query execution.
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/metadata/HandleResolver.java
> +         * @return the class used to tell the partition scheme of the query execution
```suggestion
         * @return the class used to inform the partition scheme about the query execution
```
```suggestion
         * @return the class used to tell the partition scheme of the query execution
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/metadata/DynamicCatalogStoreRoundRobin.java
> +     * data connections(catalogs). If the instance that server executed the request is down,
```suggestion
     * data connections (catalogs). If the instance that server executed the request is down,
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/metadata/DynamicCatalogStoreRoundRobin.java
> +     * or the server tried to execute a request to all API instances.
```suggestion
     * or if the server already tried to execute a request to all API instances.
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/metadata/CatalogManager.java
> +     * Gets the list of all existed catalogs inside the server.
```suggestion
     * Gets the list of all existing catalogs inside the server.
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/metadata/CatalogManager.java
> +     * @return the list of all existed catalogs inside the server
```suggestion
     * @return the list of all existing catalogs inside the server
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/memory/MemoryPoolAssignmentsRequest.java
> +     * It is used to discover which machine(node) is the
```suggestion
     * Used to discover which machine (node) is the
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQuery.java
> +     * Gets the futures that represent the query dispatch operation to be executed
```suggestion
     * Gets the futures that represent the query dispatch operation to be executed.
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/execution/SqlTask.java
> +     * the last heartbeat is increases.
```suggestion
     * the last heartbeat increases.
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/execution/SqlTask.java
> +     * It will checks if the holder contains any executing task and will
```suggestion
     * Checks if the holder contains any executing task and will
```

2020-10-28 14:14 UTC, joaopedro-simbiose commented on presto-main/src/main/java/io/prestosql/execution/StateMachine.java
> +     * It executes the thread and if the server is shutting down
```suggestion
     * Executes the thread and if the server is shutting down
```

2020-11-04 14:31 UTC, anthonylouisbsb commented on presto-main/src/main/java/io/prestosql/sql/planner/OrderingScheme.java
> +     * Gets the all ORDER BY clauses.
Description added

2020-11-04 14:35 UTC, anthonylouisbsb commented on presto-main/src/main/java/io/prestosql/server/TaskResource.java
> +    /**
added

2020-11-04 15:10 UTC, merged